const state={started:false,trigger:null,step:'idle',score:12,lead:{name:'Instagram Follower',goal:null,offer:null,experience:null,timeline:null,problem:null,commitment:null,booked:null}};
const els={chat:document.getElementById('chatLog'),starterArea:document.getElementById('starterArea'),form:document.getElementById('messageForm'),input:document.getElementById('messageInput'),send:document.getElementById('sendBtn'),reset:document.getElementById('resetBtn'),score:document.getElementById('scoreValue'),scoreFill:document.getElementById('scoreFill'),scoreReason:document.getElementById('scoreReason'),temp:document.getElementById('leadTemp'),stage:document.getElementById('stageBadge'),goal:document.getElementById('goalValue'),offer:document.getElementById('offerValue'),experience:document.getElementById('experienceValue'),timeline:document.getElementById('timelineValue'),problem:document.getElementById('problemValue'),commitment:document.getElementById('commitmentValue'),summary:document.getElementById('summaryText'),timelineEvents:document.getElementById('eventTimeline'),handover:document.getElementById('handoverCard')};
const triggerCopy={story:{user:'🔥 auf deine Coaching-Story reagiert',event:'Story-Reaktion erkannt',opening:'Hey 👊 danke für die Reaktion. Geht es dir gerade eher um Fitness/Performance, besseres Kämpfen oder eine konkrete Wettkampfvorbereitung?'},comment:{user:'COACHING',event:'Kommentar „COACHING“ erkannt → private DM gestartet',opening:'Hey 👊 hab deinen COACHING-Kommentar gesehen. Was willst du aktuell am stärksten verbessern?'},dm:{user:'Hey, ich will im Kampfsport aufs nächste Level.',event:'Direkte Instagram-DM eingegangen',opening:'Stark. Lass mich kurz checken, was bei dir am meisten Sinn macht 👊 Was ist aktuell dein Hauptziel?'}};
const questions={goal:{replies:['Fitness & Performance','Kampfsport verbessern','Konkreter Fight']},experience:{replies:['Unter 1 Jahr','1–3 Jahre','3+ Jahre / Wettkampf'],prompt:'Wie lange trainierst du schon ungefähr?'},timeline:{replies:['Sofort starten','In 4–8 Wochen','Erstmal informieren'],prompt:'Wann willst du das Thema wirklich angehen?'},problem:{replies:['Kondition','Technik & Taktik','Weight Cut','Konstanz & Struktur'],prompt:'Was bremst dich aktuell am stärksten? Du kannst auch frei antworten.'},commitment:{replies:['Ja, wenn es passt','Ich will ernsthaft starten','Kommt auf das Angebot an'],prompt:'Wenn es fachlich und menschlich passt: Wärst du bereit, die nächsten Wochen strukturiert mit Coach-Begleitung zu arbeiten?'}};
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
function addUserMessage(text){const tpl=document.getElementById('userBubbleTemplate').content.cloneNode(true);tpl.querySelector('.user-bubble').textContent=text;els.chat.appendChild(tpl);scrollChat()}
function addBotMessage(text){const tpl=document.getElementById('botBubbleTemplate').content.cloneNode(true);tpl.querySelector('.bot-bubble').textContent=text;els.chat.appendChild(tpl);scrollChat()}
function addTyping(){const tpl=document.getElementById('botBubbleTemplate').content.cloneNode(true);const row=tpl.querySelector('.message-row');row.dataset.typing='true';row.querySelector('.bot-bubble').innerHTML='<span class="typing"><i></i><i></i><i></i></span>';els.chat.appendChild(tpl);scrollChat()}
function removeTyping(){els.chat.querySelector('[data-typing="true"]')?.remove()}
async function botSay(text,delay=520){addTyping();await sleep(delay);removeTyping();addBotMessage(text)}
function scrollChat(){requestAnimationFrame(()=>{els.chat.scrollTop=els.chat.scrollHeight})}
function addQuickReplies(items,handler){const tpl=document.getElementById('quickRepliesTemplate').content.cloneNode(true);const wrap=tpl.querySelector('.quick-replies');items.forEach(label=>{const btn=document.createElement('button');btn.type='button';btn.textContent=label;btn.addEventListener('click',()=>{wrap.querySelectorAll('button').forEach(b=>b.disabled=true);handler(label)});wrap.appendChild(btn)});els.chat.appendChild(tpl);scrollChat()}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function addEvent(text,isMuted=false){if(els.timelineEvents.querySelector('.muted-event'))els.timelineEvents.innerHTML='';const div=document.createElement('div');div.className=`event${isMuted?' muted-event':''}`;div.innerHTML=`<span></span><p>${escapeHtml(text)}</p>`;els.timelineEvents.prepend(div)}
function setScore(value,reason){state.score=Math.max(0,Math.min(100,value));els.score.textContent=state.score;els.scoreFill.style.width=`${state.score}%`;els.scoreReason.textContent=reason;els.temp.className='temperature '+(state.score>=78?'hot':state.score>=45?'warm':'cold');els.temp.textContent=state.score>=78?'🔥 Hot Lead':state.score>=45?'Warm':'Kalt'}
function setFlow(stage){const order=['trigger','conversation','qualified','booked'];const idx=order.indexOf(stage);document.querySelectorAll('.flow-step').forEach((el,i)=>el.classList.toggle('active',i<=idx))}
function updateLeadUI(){els.goal.textContent=state.lead.goal||'—';els.offer.textContent=state.lead.offer||'—';els.experience.textContent=state.lead.experience||'—';els.timeline.textContent=state.lead.timeline||'—';els.problem.textContent=state.lead.problem||'—';els.commitment.textContent=state.lead.commitment||'—'}
function mapOffer(goal){const n=goal.toLowerCase();if(n.includes('fight')||n.includes('wettkampf'))return'Fight Camp Coaching';if(n.includes('kampf')||n.includes('technik'))return'Combat Coaching';return'Performance Coaching'}
function inferGoal(text){const t=text.toLowerCase();if(/fight|kampf|wettkampf|camp|bout/.test(t))return t.includes('konkret')||t.includes('fight')||t.includes('wettkampf')?'Konkreter Fight':'Kampfsport verbessern';if(/mma|bjj|box|muay|kickbox|grappl|technik|sparring/.test(t))return'Kampfsport verbessern';if(/fitness|performance|kondition|shape|abnehmen|stärker|kraft/.test(t))return'Fitness & Performance';return text.length>2?text:'Kampfsport verbessern'}
function buildSummary(){const bits=[];if(state.lead.goal)bits.push(`Ziel: ${state.lead.goal}`);if(state.lead.experience)bits.push(`${state.lead.experience} Erfahrung`);if(state.lead.timeline)bits.push(`Start: ${state.lead.timeline}`);if(state.lead.problem)bits.push(`Hauptthema: ${state.lead.problem}`);if(state.lead.commitment)bits.push(`Commitment: ${state.lead.commitment}`);const offer=state.lead.offer?` Empfohlen: ${state.lead.offer}.`:'';els.summary.textContent=bits.length?`${bits.join(' · ')}.${offer}`:'Sobald der Setter genug Kontext hat, entsteht hier automatisch das Briefing für den Verkaufscall.'}
async function startConversation(trigger){if(state.started)return;state.started=true;state.trigger=trigger;state.step='goal';els.starterArea.classList.add('hidden');els.input.disabled=false;els.send.disabled=false;addUserMessage(triggerCopy[trigger].user);addEvent(triggerCopy[trigger].event);setFlow('conversation');els.stage.textContent='Im Gespräch';setScore(24,'Instagram-Interaktion + Gespräch gestartet.');await botSay(triggerCopy[trigger].opening,650);askCurrentQuestion();els.input.focus()}
function askCurrentQuestion(){const q=questions[state.step];if(q)addQuickReplies(q.replies,answer=>handleAnswer(answer))}
async function handleAnswer(text){if(!state.started||['booking','booked'].includes(state.step))return;addUserMessage(text);const current=state.step;if(current==='goal'){state.lead.goal=inferGoal(text);state.lead.offer=mapOffer(state.lead.goal);updateLeadUI();buildSummary();addEvent(`Intent erkannt → ${state.lead.offer}`);setScore(39,'Klares Ziel und passendes Coaching erkannt.');state.step='experience';await botSay(`Verstanden. ${state.lead.offer} klingt dafür am passendsten. ${questions.experience.prompt}`,560);askCurrentQuestion();return}if(current==='experience'){state.lead.experience=text;updateLeadUI();buildSummary();addEvent(`Erfahrungslevel erfasst → ${text}`);setScore(51,'Ziel + Erfahrungslevel qualifiziert.');state.step='timeline';await botSay(questions.timeline.prompt,500);askCurrentQuestion();return}if(current==='timeline'){state.lead.timeline=text;updateLeadUI();buildSummary();addEvent(`Zeitraum erfasst → ${text}`);setScore(/sofort|4–8/.test(text.toLowerCase())?67:58,'Zeitlicher Bedarf wurde erkannt.');state.step='problem';await botSay(questions.problem.prompt,520);askCurrentQuestion();return}if(current==='problem'){state.lead.problem=text;updateLeadUI();buildSummary();addEvent(`Pain Point erfasst → ${text}`);setScore(76,'Problem, Ziel und Timing sind klar.');state.step='commitment';await botSay(questions.commitment.prompt,560);askCurrentQuestion();return}if(current==='commitment'){state.lead.commitment=text;updateLeadUI();buildSummary();addEvent(`Commitment bestätigt → ${text}`);setScore(/ernsthaft|ja/i.test(text)?92:84,'Hohe Kaufnähe: Bedarf, Timing und Commitment passen.');els.stage.textContent='Qualifiziert';setFlow('qualified');state.step='booking';await botSay(`Passt. Dann macht ein kurzer Call mit Niklas Sinn. Ich geb dir direkt ein paar freie Slots – dann könnt ihr schauen, ob ${state.lead.offer} wirklich zu dir passt.`,650);addBooking()}}
function addBooking(){const tpl=document.getElementById('bookingTemplate').content.cloneNode(true);const slots=tpl.querySelector('.booking-slots');['Di · 18:30','Mi · 12:15','Do · 17:00'].forEach(slot=>{const btn=document.createElement('button');btn.type='button';btn.textContent=slot;btn.addEventListener('click',async()=>{slots.querySelectorAll('button').forEach(b=>{b.disabled=true;b.classList.remove('booked')});btn.classList.add('booked');state.lead.booked=slot;state.step='booked';els.stage.textContent='Call gebucht';setFlow('booked');setScore(97,'Qualifizierter Lead + Termin gebucht.');addEvent(`Call gebucht → ${slot}`);buildSummary();els.summary.textContent+=` Call gebucht: ${slot}.`;els.handover.classList.remove('hidden');await botSay(`Perfekt 👊 ${slot} ist reserviert. Niklas bekommt vor dem Call direkt eine Zusammenfassung aus unserem Gespräch.`,450)});slots.appendChild(btn)});els.chat.appendChild(tpl);scrollChat()}
els.form.addEventListener('submit',event=>{event.preventDefault();const text=els.input.value.trim();if(!text||els.input.disabled)return;els.input.value='';handleAnswer(text)});
document.querySelectorAll('[data-trigger]').forEach(btn=>btn.addEventListener('click',()=>startConversation(btn.dataset.trigger)));
els.reset.addEventListener('click',()=>location.reload());
updateLeadUI();
